# Archivo de configuración para desplegar el asistente Olivia en Render.com

services:
  # Cambiado de 'web' a 'worker' porque el bot ya no usa webhooks.
  - type: worker 
    name: asistoliv
    env: python

    # Comando para instalar todas las dependencias.
    buildCommand: "pip install -r requirements.txt"

    # Comando para iniciar el bot.
    startCommand: "python main.py"

    # Variables de entorno.
    # Los secretos (tokens, API keys) se gestionan desde el dashboard.
    envVars:
      # Fija la versión de Python para asegurar la compatibilidad.
      - key: PYTHON_VERSION
        value: "3.11.11" # Seamos específicos con la versión
